remote_theme      : pages-themes/hacker@v0.2.0
plugins           : [jekyll-remote-theme, jekyll-feed]

title             : dms-g
description       : just human with nothing to do
lang              : eng
timezone          : Asia/Jakarta
show_downloads    : false
encoding          : utf-8
show_drafts       : false 
future            : true
port              : 443
livereload        : true


defaults:
  - scope:
      path: ""
      type      : default
    values:
      layout    : default
      toc       : false 
      permalink : /:title/
  - scope:
      path      : "_posts"
      type      : posts
    values:
      layout    : post
      toc       : true 
      permalink : /posts/:title/
  