remote_theme      : pages-themes/hacker@v0.2.0
plugins           :
- jekyll-remote-theme
- jekyll-feed

title             : dms-g
description       : just human with nothing to do
timezone          : Asia/Jakarta
show_downloads    : false
disable_disk_cache: false
exclude           : [_config.yml]
encoding          : utf-8
show_drafts       : false
future            : true
baseurl           : https://dms-g.github.io/
port              : 443
livereload        : true
